// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

// Character Data
type Character struct {
	ID        int    `json:"_id"`
	Name      string `json:"name"`
	Image     string `json:"image"`
	SplashArt string `json:"splashArt"`
}
